### ISSUE TITLE
AUC_Bailer_method Quesiton

### ISSUE THREAD

**Issue by j9cc** [john-harrold/ubiquity-pkpd#3]
Hi, I tried to use the Bailer method to calculate the standard deviation of AUC.
But I got the error messages as follows:
![Screenshot 2024-05-15 at 11 46 33 AM](https://github.com/john-harrold/ubiquity-pkpd/assets/125993080/0c130ad7-5e61-4a02-b88d-e0e83e4bc6c4)

**Comment by john-harrold** [comment]
I'll provide you with a quick solution and if you're interested some other
options.


# The quick solution:

The reason you cannot use that function directly is because it's an internal
function and it isn't exported by the package. The simplest solution is just
to copy the function definition and paste it into your script somewhere above
the function call:

This is a link to the location for the source of the function:
https://github.com/john-harrold/ubiquity/blob/1c7858f4e688c0e68d3e6cee910b12d4bd3d944f/R/ubiquity.r#L9769


This is the function definition:

```r
AUC_Bailers_method = function(conc_data  = NULL, 
                              dsmap      = list(NTIME       = "NTIME", 
                                                CONC        = "CONC", 
                                                ID          = "ID")){
res     = list() 
msgs    = c()
isgood  = TRUE
        
AUC     = NULL
var_AUC = NULL 
r       = NULL
obs     = NULL
times   = NULL



# Making sure that the conc_data input is a data frame
if(!is.data.frame(conc_data)){
  isgood = FALSE
  msgs = c(msgs, "conc_data must be a data frame")
}
    

req_cols = c("NTIME", "CONC", "ID")

# Checking the contents of dsmap
for(cname in req_cols){
  if(!(cname %in% names(dsmap))){
    isgood = FALSE 
    msgs = c(msgs, paste("column: >", cname, "< not foundin dsmap", sep=""))
  }
}

# making sure that the columns specified in dsmap are found in conc_data
if(isgood){
  for(cname in names(dsmap)){
    if(!(dsmap[[cname]] %in% names(conc_data))){
      isgood = FALSE
      msgs = c( msgs, paste("column: >", dsmap[[cname]], "< not found in conc_data", sep = ""))
    }
  }
}

# Calculating the AUC
if(isgood){
  IDs     = unique(conc_data[[dsmap$ID]])
  IDs_str = paste("sub_", IDs, sep="")
  Times   = sort(unique(conc_data[[dsmap$NTIME]]))

  K = length(Times)
  R = length(IDs)

  # Putting the data into sparse matrix form:
  #  - A column for each ID
  #  - Row for each time


  obs   = matrix(ncol=R, nrow=K, data = -1)
  colnames(obs) <- IDs_str

  # Walking through the data to populating the concentrations
  for(ID in IDs){
    ID_str = paste("sub_", ID, sep="")
    for(Time in Times){
      if(nrow(conc_data[conc_data[[dsmap$NTIME]] == Time & conc_data[[dsmap$ID]] == ID, ]) == 1){
         concval = conc_data[conc_data[[dsmap$NTIME]] == Time & conc_data[[dsmap$ID]] == ID, ][[dsmap$CONC]]
         obs[Times == Time, ID_str] = concval
      }
      if(nrow(conc_data[conc_data[[dsmap$NTIME]] == Time & conc_data[[dsmap$ID]] ==  ID, ]) > 1){
         isgood = FALSE
         msgs = c(msgs, paste("At time", Time, " subject ", ID, " had more than 1 observation", sep="" ))
      }
    }
  }

  # calculating the weight vector
  #   w1 = (t(2)   -   t(1)  )/2 
  #   wk = (t(k+1) -   t(k-1))/2    k = [2,K-1];
  #   wk = (t(K)   -   t(K-1))/2 
  
  w   = rep(0, K)
  r   = rep(0, K)
  u   = rep(0, K)
  ssq = rep(0, K)

  w[1] = (Times[2]-Times[1  ])/2
  w[K] = (Times[K]-Times[K-1])/2

  for(k_idx in c(1:K)){

    # Calculating the weights for the numbers in between
    # the first and last elements
    if((k_idx > 1) & (k_idx < K)){
      w[k_idx] = (Times[k_idx+1]-Times[k_idx-1])/2
    }
    # nonzero elements for the row:
    nz_elements =  as.numeric(obs[k_idx, obs[k_idx,] > 0 ])

    # number of samples per time point
    r[k_idx] = length(nz_elements)

    # mean concentration for the current time point
    u[k_idx] = mean(nz_elements)

    # variance of the time point
    ssq[k_idx] = var(nz_elements)

  }

  AUC     = sum(w*u)
  var_AUC = sum(w^2*ssq/r)
}

if(!isgood){
  msgs = c(msgs, "ubiquity::AUC_Bailers_method()")
}

res$AUC     = AUC
res$var_AUC = var_AUC
res$r       = r
res$isgood  = isgood
res$msgs    = msgs
res$obs     = obs
res$times   = times

res}
```


# PKNCA solution

Within ubiquity I generally use the PKNCA package for doing NCA. When I
created this part of ubiquity there were certain features in PKNCA that were
not working. For example there was no support for sparse sampling, so I
created that function above to do it for me :). However, PKNCA has since added
this functionality and it pretty much does what I need now. So you have
another solution. You can use PKNCA.

https://billdenney.github.io/pknca/articles/v04-sparse.html

# A future solution 

I'm in the process of creating a set of shiny tools called ruminate. One part
of that is a shiny module for NCA. The down side is that the sparse sampling
support is broken right now. But I will try to get it fixed over the weekend.
At a high level what ruminate does is 

- Provides a point and click interface to different tools (dplyr, tidyr,
  ggplot and of course PKNCA)

- Generates code on the fly to help you learn how to use those tools

- Dumps results directly into reports (Word, PowerPoint and Excel)

- Generates a script to reproduce everything you do in the UI

- Allows you to save and load your analysis later

Package site:
https://ruminate.ubiquity.tools/

Video (no audio) showing how to use it:
https://useruminate.ubiquity.tools/

You can run ruminate on your laptop or deploy it. This is an instance running
online for testing:
https://runruminate.ubiquity.tools/


Eventually I want to move the NCA support out of ubiquity and just provide
ruminate for this.

**Comment by j9cc** [comment]
Hi,
  Thanks for the quick reply.
  Yes, I also figured out PKNCA added sparse sampling AUC calculation.
  I did it in PKNCA, I didn't use that in the beginning because PKNCA didn't specify it used the Bailer method but the formula is actually the same if assuming one sample from one subject.
  Thank you very much!
  Looking forward to your shiny tools! Will definitely try it out.

**Comment by john-harrold** [comment]
Cool. I'm glad it's working for you. 

I think I have the bug worked out, so I should be able to push a fix to github and update runruminate.ubiquity.tools test site over the weekend.

**Comment by john-harrold** [comment]
Howdy j9cc,

This is fixed in the development version and the one deployed online (runruminate.ubiquity.tools). I'll try to submit it to CRAN next week sometime. Here is a short video showing how to do sparse analysis and get the outputs:

https://vimeo.com/947421240

John

**Comment by j9cc** [comment]
Hi John,

  I played around with my own data set.
  Several problems I encountered or some suggestions (It could be my problem of not familiar with how everything works):


  1.  My data format is in NONMEM format, has multiple drugs, and the mean concentration is not calculated. I used to do it in R directly. My raw csv file only has concentration from each subject. For data visualize option, I want to plot the mean concentration in lines and possibly with error bars for each drug. I tried to use the transform data option, I think it is doable but a bit repetitive to calculate the mean concentration and standard error using the alter option (looks like mutate from dplyr). If there is an option to calculate mean concentration and standard error based on customization group would be great.



  1.  After transformed my data, I tried to run NCA. But there were some issues and I had to redo the data transformation again. But it is not cleared which transformed data is subject to the second NCA run. Please see the attached screenshot: [A screenshot of a computer  Description automatically generated]

It indicates that the data is from PH. It would be helpful if we could select which “transformed” data is subject to NCA run.

For example, the default transformed data ruminate created is data_view_2 or data_view_1.



Hope that I explained it clearly.

  Will let you know if anything else comes up during my runs.
  Thanks for creating this again. It is interesting that we have option other than Winnonlin.


Regards,
Hsien-Wei (Eric) Huang


From: John Harrold ***@***.***>
Date: Friday, May 17, 2024 at 10:14 AM
To: john-harrold/ubiquity-pkpd ***@***.***>
Cc: j9cc ***@***.***>, State change ***@***.***>
Subject: Re: [john-harrold/ubiquity-pkpd] AUC_Bailer_method Quesiton (Issue #3)

Howdy j9cc,

This is fixed in the development version and the one deployed online (runruminate.ubiquity.tools). I'll try to submit it to CRAN next week sometime. Here is a short video showing how to do sparse analysis and get the outputs:

https://vimeo.com/947421240

John
